### ISSUE TITLE
Remove GPShell dependency

### ISSUE THREAD

**Issue by bitgamma** [status-im/status-keycard#32]
GPShell is becoming more and more difficult to install on modern computers. We can rewrite applet installation using our own SDK.

**Comment by martinpaljak** [comment]
(Shameless plug: you could also try using GlobalPlatformPro, or chime in where it lacks)

**Comment by bitgamma** [comment]
@martinpaljak GlobalPlatformPro is great, and would actually work well for this task, when using Gradle.

We have also implemented a small part of the GlobalPlatform specs in our [SDK](https://github.com/status-im/status-keycard-java) to install the applet not only on systems supporting javax.smartcardio but also on Android with its NFC interface (which unfortunately does not implement the javax.smartcardio package).

In our SDK we achieved compatibility by having our own APDU/Channel objects and creating a bridge for both API. It'd be great if GlobalPlatformPro adopted a similar solution, since it could then be used without javax.smartcardio.

**Comment by martinpaljak** [comment]
I'm a strong believer of BIBO (bytes in, bytes out) for communication, like IsoDep `byte[] transmit(byte[])` but the CommandAPDU/ResponseAPDU payload parsing functions are actually pretty useful. There are projects out there that re-implement it. In theory, the "tool" class of GPPro should be the only dependant on javax.smartcardio for _transmit_ part. For Android - in "serious" environments there are no keys to handle on the phone but on the backend, thus the only operation an Android should do is to channel APDU-s to a remote backend.

**Comment by ligi** [comment]
> For Android - in "serious" environments there are no keys to handle on the phone but on the backend, thus the only operation an Android should do is to channel APDU-s to a remote backend.

can you elaborate on this?

**Comment by martinpaljak** [comment]
Unless doing simple test/development installation, but actually having global platform key management, client device should be dealing with sending byte blobs of APDU-s back and forth between an entity who actually holds the keys to the card - which is usually a backend, with standard java (and access to a HSM)

Nevertheless, it would be cool to extend usage. But the focus of GPPro has been as a developer tool (on a desktop) or as a backend library (in a server), never within a client app within an untrusted phone. If the android device is handled as a developer tool, it is obviously another story.

I might look into splitting more of the code to make sure that just the CLI tool depended on javax.smartcardio *for transmit*. javax.smartcardio.Command/ResponseAPDU are still neat classes I don't think one should re-create by default. Rather use something that re-implements them on Android.

**Comment by ligi** [comment]
>  untrusted phone.

I trust my phone way more than any backend ;-)

**Comment by bitgamma** [comment]
Indeed storing the ISD keys on the Android device could be unsafe but is very useful during the development phase (using the default keys). 

However when the user is the owner of the SmartCard (unlike the usual case, where the issuer is the owner and the user is the "holder") then one wants to allow certain degrees of freedom and maybe add a different way to verify authenticity/integrity of the installed applets.

There are also scenarios with SSD/DM/DAP where having the Android-based device (which is not necessarely a phone btw) handle the keys of a specific SSD is perfectly fine.
