### ISSUE TITLE
Trusted JCOP implementation

### ISSUE THREAD

**Issue by nikolobok** [status-im/status-keycard#33]
Any javacard smartcard is based on closed source JCOP implementation.
How JCOP is deployed to smartcard eeprom and could it be theoretically replaced with one compiled from sources?

**Comment by nikolobok** [comment]
So this project have no sense..?

**Comment by bitgamma** [comment]
Why would that be?

**Comment by Nucnay3428** [comment]
I'm not sure what to do this im struggling to get a grip on my account

**Comment by Nucnay3428** [comment]
Help
