### ISSUE TITLE
PUK retry counter not honoured

### ISSUE THREAD

**Issue by karalabe** [status-im/status-keycard#37]
The latest 2.2.1 release of the keycard app permits an unlimited number of PUK retries. At least definitely not 5 as it's speced in the source code, as I've tried at least 25 wrong ones and then the good PUK still lets me in.

**Comment by bitgamma** [comment]
Tomorrow I will try. In the meantime can you please attach the log? 

In particular, the PUK is compared (and thus the counter decreased) only if the APDU has the correct length (18 digits, 12 for the PUK and 6 for the PIN) and is composed of all numeric digits. If you get 0x6A80 it means the PUK has not been tried and does not count as an attempt.

If you instead get 0x63cX (where X is the number of remaining tries) then it has been tried, and if you can do it more than 5 times then it is a bug, although with a quick code review I cannot see this problem happening.

**Comment by bitgamma** [comment]
I tested and I cannot reproduce the issue. At every PUK attempt I get 0x63CX from 4 to 0. Then entering the correct PUK still gives 0x63C0, which is the expected behaviour. As I mentioned before, I'd need to see your log, but I guess you are getting a different error so the PUK is not even being tested.

**Comment by karalabe** [comment]
Hey, played around with it a bit more and can confirm that the PUK is properly decremented if I supply all the needed 12 + 6 bytes.

However, then I have a different issue:

 * In [`unblockPIN`](https://github.com/status-im/status-keycard/blob/master/src/main/java/im/status/keycard/KeycardApplet.java#L615), you verify that the PUK + PIN is 18 digits, and don't fail the PUK attempt if the input is bad. This is imho good behavior.
 * If [`verifyPIN`](https://github.com/status-im/status-keycard/blob/master/src/main/java/im/status/keycard/KeycardApplet.java#L528) however you  do not check that the length is 6 digitas, so you **do** fail the PIN attempt if the input is bad.

I think both behaviors is fine as long as they are consistent across each other. At least this is what I would expect.
