### ISSUE TITLE
Status Keycard compatibles wallets ?

### ISSUE THREAD

**Issue by prodnet** [status-im/status-keycard#39]
Hello,

What are the current wallets compatible and who have integrated the keycard as a hardware wallet?

When will be  ready the first pubic version of Keycard hardware crypto wallet ?
(Compatible with all Major Cryptocurrencies, Ethereum, ERC20 tokens, Bitcoin, Bitcoin Cash, Litecoin, Ripple, ...etc.)

**Comment by guylouis** [comment]
There are several of wallet currently integrating Keycard, and the first one that will come in beta are probably walleth and status.

Also note that Geth has also Keycard support.

**Comment by ligi** [comment]
WallETH with keycard support should land this week. You can see a hint of it here: https://twitter.com/wallethapp/status/1118375263132426247

**Comment by prodnet** [comment]
Hey,
Please tell me how to use the keycard with your application?
I can not configure it with WallETH, can you tell me how to set it up?
Thanks.

**Comment by ligi** [comment]
You create a new Account
Select "Connect Via NFC"
the rest should be self explaining 
let me know when you face problems

**Comment by prodnet** [comment]
How can I see and store the seed mnemonic words?

**Comment by ligi** [comment]
you can't - that would defeat the purpose

**Comment by prodnet** [comment]
So if the card is lost, can not you recover the funds?

**Comment by ligi** [comment]
the card must be duplicated like this:

https://status.im/keycard_api/sdk_duplication.html

that said - this feature is not yet available in WallETH. I see the current support more as a starting point for people to try it out with testnets or very small amounts (like cash that is also gone when you loose it)
But exposing the key to the phone (which you would need to to to show the mnemonic) defeats the purpose in my eyes.

**Comment by prodnet** [comment]
Ok i see ...
Perhaps there is an opportunity to reconstitute the secret using the Shamir Secret Sharing Scheme ...
(several keycards, could be used in the reconstitution procedure)

**Comment by IvanClementino** [comment]
> You create a new Account
> Select "Connect Via NFC"
> the rest should be self explaining
> let me know when you face problems

Hi!
Can I import other accounts from the keycard besides the main one?

**Comment by Joffythetrophy** [comment]
Can we use this keycard to pay at terminals.  At local stores like tap and Pay after It's been integrated with a wallet?if not when? Or do I have to find a dapp  payment  tool?
