### ISSUE TITLE
Compilation error: package javax.smartcardio is not visible

### ISSUE THREAD

**Issue by anwfr** [status-im/status-keycard#49]
Hello,
I followed the compilations instructions.
When running `./gradlew convertJavacard` (JDK 10.0.2) I get the following error:

> /java-applet/buildSrc/src/main/java/im/status/keycard/build/InstallTask.java:12: error: package javax.smartcardio is not visible
> import javax.smartcardio.*;
>             ^
>   (package javax.smartcardio is declared in module java.smartcardio, which is not in the module graph)
> /java-applet/buildSrc/src/main/java/im/status/keycard/build/InstallTask.java:49: error: cannot access CardChannel
>     PCSCCardChannel sdkChannel = new PCSCCardChannel(apduCard.getBasicChannel());
>                                  ^
>   class file for javax.smartcardio.CardChannel not found
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':buildSrc:compileJava'.
> > Compilation failed; see the compiler error output for details.

Any idea?
>

**Comment by bitgamma** [comment]
Keycard should be compiled using Java 8. SmartCard I/O is likely an optional module after Java 9 (because of project Jigsaw) and its usage must be declared.

**Comment by anwfr** [comment]
Thank you very much
