### ISSUE TITLE
Make the number of attempts before PIN lock down configurable

### ISSUE THREAD

**Issue by guylouis** [status-im/status-keycard#62]
Today this number is 3 and hardcoded. 
This could be setup as a parameter of the INIT command https://status.im/keycard_api/apdu/init.html

**Comment by bitgamma** [comment]
maybe we should limit the configurable value to some upper maximum and lower minimum though. I'd say to accept values between 2 and 10. Wdyt?

**Comment by guylouis** [comment]
makes sense !
