### ISSUE TITLE
Docs dead link

### ISSUE THREAD

**Issue by Aiosa** [status-im/status-keycard#64]
Documentation link `https://keycard.status.im/api/` in README is dead. Please update.
Thanks

**Comment by Aiosa** [comment]
Also, an URL to 'android installer' targets discontinued project that has readme-redirect link to another repo, so could be updated as well... Unless it is intended, in that case, it would be a good idea to say(write) so.

**Comment by bitgamma** [comment]
Thanks for the report, fixed!
