### ISSUE TITLE
Update readme 'HOST section'

### ISSUE THREAD

**Issue by Aiosa** [status-im/status-keycard#65]
Hello,

it would be really helpful to write down compatible host apps so that the card can be really used. Now one has to search for hours an app to use the card with - if you have WallETH, say so. If you have more (I was unable to find), say so. I spent 2 hours searching for compatible hosts. Even Status app does not seem to support it.

Thanks!

**Comment by bitgamma** [comment]
added the list of apps with links in the "Where to start" section of the README.
