### ISSUE TITLE
Plausible deniability

### ISSUE THREAD

**Issue by ligi** [status-im/status-keycard#7]
as talked about the magicians gathering after cryptolife: It would be great to be able to specify N>=1 PINs to lead to different derivation paths to gain plausible deniability.

**Comment by bitgamma** [comment]
Will do, I am back from Prague and I am organizing all the discussed items to start working on them.

**Comment by cryptoida** [comment]
Did you decide to implement  a plausible deniability option?

**Comment by bitgamma** [comment]
we are now focusing on other aspects, but in the future it will come

**Comment by cryptoida** [comment]
This functionality is indispensable and for some clients like me it would be the only reason why I would not adopt the keycard project ....I hope to be integrated soon :)

**Comment by cryptoida** [comment]
Hello,
Haven't implemented this plausible deniability option yet?
Thank you !

**Comment by guylouis** [comment]
We have not yet, indeed, since it's been on the lower priority list, especially compared to enabling payment scenarios in keycard. 
However, this is interesting, could you elaborate on the use case you'd have with a keycard that implements a plausible deniability feature ?

**Comment by cryptoida** [comment]
Personally, I can't imagine a hardware wallet, without the implementation of plausible deniability.
This functionality should BE indispensable, but not only optional.
There are multiple reasons: protection against any form of constraint :oversight, government constraint, hacking, blackmail)

**Comment by willianpaixao** [comment]
Hello, @guylouis @bitgamma maybe we could try to get this done? I can help.

**Comment by bitgamma** [comment]
finally implemented card-side, will need proper wallet support.

i.e. the wallet app should not reveal the public key/address in any way before authentication and be ready that an "unexpected" public key will be used, otherwise an attacker could easily verify that the address does not match if they are using the card holder's mobile to check.

**Comment by willianpaixao** [comment]
cc @ligi @gballet for visibility.

**Comment by ligi** [comment]
Really nice - will you cut a release with this feature?

**Comment by bitgamma** [comment]
sure, we will cut a release soon
