### ISSUE TITLE
FAQ has wrong Q/A

### ISSUE THREAD

**Issue by Cygnusfear** [status-im/status-keycard#73]
I'm convinced this is not the correct answer to the question 😉

<img width="1123" alt="Screenshot 2020-12-25 at 18 29 19" src="https://user-images.githubusercontent.com/2925132/103140503-2659c200-46df-11eb-8288-45536472fe4e.png">

Happy holidays 😀

**Comment by guylouis** [comment]
Thanks for the heads-up, I have corrected it
