### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by piccdk** [status-im/status-keycard#88]
Hello!

I noticed a bug on the Status keycard app. 

I have 3000 tokens of FLX, contract 0x3ea8ea4237344c9931214796d9417af1a1180770.

This is worth around $100, but your app is showing that it's worth 47K. 

It is the right token, as I double checked the contract. It's showing up the correct price on CMC, CG and Debank, but just not on your app. There must be something going on with the API that you're using and it's fetching some other token somehow.

Cheers

**Comment by guylouis** [comment]
closed and opened a similar issue in status-mobile repo 
https://github.com/status-im/status-mobile/issues/16129
